# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CICD Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Instalar Python3
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Instalar Dependencias
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Ejecutar tests con coverage
      run: |
         python -m pytest --cov=. --cov-report=html

    - name: Generar archivo de build
      run: |
        mkdir build
        cp calc.py build/

    - name: Subir artefacto Coverage
      uses: actions/upload-artifact@v4
      with:
        name: reporte-coverage
        path: htmlcov/

    - name: Subir artefacto
      uses: actions/upload-artifact@v4
      with:
        name: proyecto-build
        path: build/
